function f=Prob(Y1,Y2,varY1,varY2);
%PROB computes the log probability that Y1 and Y2 are generated by each other
numData=size(Y1,2);
det1=prod(varY1);
det2=prod(varY2);
for i=1:numData
    invMeanVar(i)=(varY1(i)+varY2(i))/(varY1(i)*varY2(i));
    p(i)=(Y1(i)-Y2(i))^2*invMeanVar(i);
end
f=-sum(p)-log(det1)-log(det2);