% File names for output and save data
% the data has to be a structure

outputFile='OC1_cluster_profile.txt';
f = fopen(outputFile,'w');
fprintf('Writing: %s\n',char(outputFile))
fprintf(f,'%s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t \n',...
	'Probe Name','Gene Name'...
	'Signal 0d', 'Signal 1d','Signal 2d','Signal 3d','Signal 4d',...
	'Signal 5d','Signal 6d','Signal 7d','Signal 8d','Signal 9d',...
	'Signal 11d','Signal 12d');
    
    
for i=1:length(cluster.an)
  fprintf(f,'%s\t %s\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t \n',...
      char(cluster.probes(i)),char(claster.an(i))...
      cluster.profile(i,1),cluster.profile(i,2),cluster.profile(i,3),...
      cluster.profile(i,4),cluster.profile(i,5),cluster.profile(i,6),...
      cluster.profile(i,7),cluster.profile(i,8),cluster.profile(i,9),...
      cluster.profile(i,10),cluster.profile(i,11),cluster.profile(i,12));
end
fclose(f)
fprintf('Done \n\n')
    
outputFile='OC1_cluster_Var.txt';
f = fopen(outputFile,'w');
fprintf('Writing: %s\n',char(outputFile))
fprintf(f,'%s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t %s\t \n',...
	'Probe Name','Gene Name'...
	'Variance 0d', 'Variance 1d','Variance 2d','Variance 3d','Variance 4d',...
	'Variance 5d','Variance 6d','Variance 7d','Variance 8d','Variance 9d',...
	'Variance 11d','Variance 12d');
    
    
for i=1:length(cluster.an)
  fprintf(f,'%s\t %s\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t %6.4f\t \n',...
      char(cluster.probes(i)),char(claster.an(i))...
      cluster.var(i,1),cluster.var(i,2),cluster.var(i,3),...
      cluster.var(i,4),cluster.var(i,5),cluster.var(i,6),...
      cluster.var(i,7),cluster.var(i,8),cluster.var(i,9),...
      cluster.var(i,10),cluster.var(i,11),cluster.var(i,12));
end
fclose(f)
fprintf('Done \n\n')
    
    
    
    
    